name: nightly

on:
  repository_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  nightly:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox==3.17.1
      - name: Run Unit tests
        run: tox -e nightly  # Run tox using latest master branch from py42/c42eventextractor

